name: 'Setup Minecraft Gradle Action'
description: 'Common setup for Minecraft Gradle project actions'
inputs:
  setup-gradle:
    description: 'Apply gradle-build-action'
    required: true
    default: 'true'
  validate-gradle-wrapper:
    description: 'Apply validate gradle wrapper action'
    required: true
    default: 'true'
  loom:
    description: 'Enable caching for loom project caches'
    required: true
    default: 'false'
  paperweight:
    description: 'Enable aching for paperweight project caches'
    required: true
    default: 'false'
  vanillagradle:
    description: 'Enable aching for VanillaGradle project caches'
    required: true
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: "validate gradle wrapper"
      uses: gradle/wrapper-validation-action@v1
      if: ${{ inputs.validate-gradle-wrapper == 'true' }}
    - name: "setup gradle"
      uses: gradle/gradle-build-action@v2
      if: ${{ inputs.setup-gradle == 'true' }}
      # gradle-build-action doesn't support caching files in the project dir
    - name: "loom cache"
      uses: actions/cache@v3
      if: ${{ inputs.loom == 'true' }}
      with:
        path: |
          .gradle/loom-cache
        key: ${{ runner.os }}-project-loom-caches-${{ hashFiles('**/libs.versions.*', '**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-project-loom-caches-
    - name: "paperweight cache"
      uses: actions/cache@v3
      if: ${{ inputs.paperweight == 'true' }}
      with:
        path: |
          **/.gradle/caches/paperweight
        key: ${{ runner.os }}-project-paperweight-caches-${{ hashFiles('**/libs.versions.*', '**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-project-paperweight-caches-
    - name: "vanillagradle cache"
      uses: actions/cache@v3
      if: ${{ inputs.vanillagradle == 'true' }}
      with:
        path: |
          .gradle/caches/VanillaGradle
        key: ${{ runner.os }}-project-vanillagradle-caches-${{ hashFiles('**/libs.versions.*', '**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-project-vanillagradle-caches-
