name: 'Minecraft Gradle Setup Action'
description: 'Setup for Minecraft Gradle projects'
inputs:
  validate-gradle-wrapper:
    description: 'Apply validate gradle wrapper action'
    required: true
    default: 'true'
  setup-gradle:
    description: 'Apply gradle-build-action'
    required: true
    default: 'true'
  loom:
    description: 'Enable caching for loom project caches'
    required: true
    default: 'false'
  paperweight:
    description: 'Enable caching for paperweight project caches'
    required: true
    default: 'false'
  vanillagradle:
    description: 'Enable caching for VanillaGradle project caches'
    required: true
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: "validate gradle wrapper"
      uses: gradle/wrapper-validation-action@v1
      if: ${{ inputs.validate-gradle-wrapper == 'true' }}
    - name: "setup gradle"
      uses: gradle/gradle-build-action@v2
      if: ${{ inputs.setup-gradle == 'true' }}
      # gradle-build-action doesn't support caching files in the project dir
    - name: "cache project local caches"
      uses: actions/cache@v3
      if: ${{ inputs.loom == 'true' || inputs.paperweight == 'true' || inputs.vanillagradle == 'true' }}
      with:
        # we cache all three in the same tarball because they will probably have similar files which can compress better together
        path: |
          .gradle/loom-cache
          .gradle/caches/VanillaGradle
          **/.gradle/caches/paperweight
        key: ${{ runner.os }}-project-local-gradle-caches-${{ hashFiles('**/libs.versions.*', '**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-project-local-gradle-caches-
